### ISSUE TITLE
Collapse All / Expand All

### ISSUE THREAD

**Issue by milsyobtaf** [thoughtbot/pipe-it-down#11]
A button to collapse all / expand all files would be 🥇 . I can see it working well either injected into the DOM or as a drop down menu from the extension icon.

Thanks for the great work, this extension is a lifesaver!

**Comment by thorncp** [comment]
Hi @milsyobtaf,

Sorry for the delay in responding. I was waiting for some changes on GitHub's end to come through, because they affect Pipe it Down. In a nutshell, GitHub now has collapse/expand as a first party feature, so Pipe it Down as-is doesn't provide much value. Additionally, they also have support for automatically collapsing certain file types. I don't know what your circumstances are, but perhaps that would a good solution for whatever is driving you to want a collapse/expand all feature. I've written more details about this at https://robots.thoughtbot.com/github-diff-supression.

That post also includes a subtle announcement of dropping support for Pipe it Down. Therefore I'm closing this issue and will be updating this repo soon to reflect its status.

If these new GitHub features don't solve your problem, I'd like to hear about why!
